lessons/PetHotel.Web/Models/DataAccess/IPetHotelDataAccess.cs
namespace PetHotel.Web.Models.DataAccess;

public interface IPetHotelDataAccess
{
    IEnumerable<Hotel> GetHotels();

    Hotel? GetHotel(long id);
    void AddHotel(Hotel hotel);
    void UpdateHotel(long id, Hotel hotel);
    void DeleteHotel(long id);
}

lessons/PetHotel.Web/Models/DataAccess/PetHotelInMemoryDataAccess.cs
using System.Text.RegularExpressions;

namespace PetHotel.Web.Models.DataAccess;

public class PetHotelInMemoryDataAccess : IPetHotelDataAccess
{
    private readonly List<Hotel> hotels =
    [
        new Hotel { Id = 1, Name = "Hotel 1", Address = "Address 1"},
        new Hotel { Id = 2, Name = "Hotel 2", Address = "Address 2"},
        new Hotel { Id = 3, Name = "Hotel 3", Address = "Address 3"},
    ];

    public IEnumerable<Hotel> GetHotels()
    {
        return hotels;
    }

    public Hotel? GetHotel(long id)
    {
        Hotel? match = null;

        foreach (var hotel in hotels)
        {
            if (hotel.Id == id)
            {
                match = hotel;
                break;
            }
        }

        return match;
    }

    public void AddHotel(Hotel hotel)
    {
        hotels.Add(hotel);

        hotel.Id = hotels.Count;
    }

    public void UpdateHotel(long id, Hotel hotel)
    {
        var match = GetHotel(id);

        if (match != null)
        {
            match.Name = hotel.Name;
            match.Address = hotel.Address;
        }
    }

    public void DeleteHotel(long id)
    {
        bool removed = false;

        for (int i = 0; i < hotels.Count && !removed; i++)
        {
            if (hotels[i].Id == id)
            {
                hotels.RemoveAt(i);
                removed = true;
            }
        }

        if (!removed)
        {
            throw new Exception($"Hotel with id {id} not found");
        }
    }
}

lessons/PetHotel.Web/Models/ErrorViewModel.cs
namespace PetHotel.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

lessons/PetHotel.Web/Models/Hotel.cs
using System.ComponentModel.DataAnnotations;

namespace PetHotel.Web.Models;

public class Hotel
{
    public long Id { get; set; }

    [StringLength(maximumLength: 128, MinimumLength = 3)]
    public string? Name { get; set; }

    public string? Address { get; set; }
}

lessons/PetHotel.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Web.Models;

namespace PetHotel.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

lessons/PetHotel.Web/Controllers/HotelsController.cs
using Microsoft.AspNetCore.Mvc;
using PetHotel.Web.Models;
using PetHotel.Web.Models.DataAccess;

namespace PetHotel.Web.Controllers;

public class HotelsController : Controller
{
    private readonly IPetHotelDataAccess dataAccess;

    public HotelsController(IPetHotelDataAccess dataAccess)
    {
        this.dataAccess = dataAccess;
    }

    public IActionResult Index()
    {
        return View(dataAccess.GetHotels());
    }

    public IActionResult Details(long id)
    {
        Hotel? match = dataAccess.GetHotel(id);

        return match == null ? NotFound() : View(match);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Hotel hotel)
    {
        if (!ModelState.IsValid)
        {
            return View(hotel);
        }

        dataAccess.AddHotel(hotel);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Edit(long id)
    {
        Hotel? match = dataAccess.GetHotel(id);

        return match == null ? NotFound() : View(match);
    }

    [HttpPost]
    public IActionResult Edit(long id, Hotel hotel)
    {
        if (!ModelState.IsValid)
        {
            return View(hotel);
        }

        dataAccess.UpdateHotel(id, hotel);

        return RedirectToAction(nameof(Details), new { id });
    }

    public IActionResult Delete(long id)
    {
        var match = dataAccess.GetHotel(id);

        return match == null ? NotFound() : View(match);
    }

    [HttpPost]
    public IActionResult ConfirmDelete(long id)
    {
        dataAccess.DeleteHotel(id);

        return RedirectToAction(nameof(Index));
    }

}

lessons/PetHotel.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

lessons/PetHotel.Web/Views/Hotels/Create.cshtml
@model Hotel

@{
    ViewData["Action"] = "Create";
}

<h1>Create hotel</h1>

<partial name="_HotelForm" model="@Model" view-data="@ViewData" />

lessons/PetHotel.Web/Views/Hotels/Delete.cshtml
@model Hotel

<h1>Delete hotel</h1>

<p>Are you sure you want to delete @Model.Name?</p>

<form asp-action="ConfirmDelete" method="post">
    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-danger">Delete</button>
</form>

lessons/PetHotel.Web/Views/Hotels/Details.cshtml
@model Hotel

<h1>Hotel details</h1>
<p>@Model.Name</p>
<p>Address: @Model.Address</p>



<a class="btn btn-link" asp-action="Index">Back</a>
<a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.Id" role="button">Edit</a>
<a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id" role="button">Delete</a>

lessons/PetHotel.Web/Views/Hotels/Edit.cshtml
@model Hotel

@{
    ViewData["Action"] = "Edit";
}

<h1>Edit hotel</h1>

<partial name="_HotelForm" model="@Model" view-data="@ViewData" />

lessons/PetHotel.Web/Views/Hotels/Index.cshtml
@model IEnumerable<PetHotel.Web.Models.Hotel>

Whoah! Hotels here

<div>
    <a class="btn btn-primary" asp-action="Create">Create</a>
</div>

<ul>
    @foreach (var hotel in Model)
    {
        <li>
            <a asp-action="Details" asp-route-id="@hotel.Id">@hotel.Name</a>
        </li>
    }
</ul>

lessons/PetHotel.Web/Views/Hotels/_HotelForm.cshtml
@model Hotel

@{
    string action = ViewData["Action"]!.ToString()!;
}

<form asp-action="@action">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Address" class="form-label"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address"></span>
    </div>
    <div class="mb-3">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <a asp-action="Index">Cancel</a>
        <span asp-validation-summary="All"></span>
    </div>
</form>

lessons/PetHotel.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetHotel.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetHotel.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetHotel.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotels" asp-action="Index">Hotels</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PetHotel.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>